Need mw-content-ltr class in addition to dir attribute
InternationalScratchWiki/SyntaxHighlight_PrismJS pull request #4
Opened 2022-03-16 17:00 UTC by ilmari-lauhakangas

Sorry I missed this earlier. If we don't include this, MW changes text-align CSS property based on the directionality of the language. https://www.mediawiki.org/wiki/Directionality_support

2022-03-16 18:27 UTC, Kenny2github requested changes
Just to be sure, add the class to the `$preTagAttrs` as well.

2022-03-16 18:50 UTC, ilmari-lauhakangas commented
Sorry, yes, it should be enough to have it in pre

2022-03-17 08:26 UTC, ilmari-lauhakangas commented
I guess squash and merge would be best for this one.

2022-03-17 21:35 UTC, Kenny2github approved these changes
I meant to have it on both, so for the sake of time I've done that myself.

2022-03-17 21:36 UTC, merged

2022-03-17 21:47 UTC, ilmari-lauhakangas commented
> I meant to have it on both, so for the sake of time I've done that myself.

I know, but I think that is superfluous.